---
deployment:
  tasks:
    - export DEPLOY_DIR=/home/lsoluti1/repositories/castro-team-web/public_html
    - echo "Instalando dependências do Angular..."
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - echo "Realizando o build da aplicação..."
    - /opt/cpanel/ea-nodejs16/bin/ng build --prod --output-path=dist
    - echo "Copiando arquivos buildados para o diretório público..."
    - rsync -a dist/ $DEPLOY_DIR/
    - echo "Deploy concluído!"
